packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"
overrides:
  kysely: 0.28.17
packageExtensions:
  "@sentry/react-native@*":
    dependencies:
      "@expo/config-plugins": ~56.0.14
allowBuilds:
  '@biomejs/biome': true
  '@heroui-pro/react': true
  '@heroui/shared-utils': true
  '@sentry/cli': true
  '@zowe/secrets-for-zowe-sdk': true
  esbuild: true
  msgpackr-extract: true
  sharp: true
